export const CONDITIONS = [
  {
    id: "diabetes_type2",
    name: "Diabetes Type 2",
    shortName: "Diabetes T2",
    color: "#E67E22",
    mealsPerDay: 5,
    mealStructure: ["breakfast","morning_snack","lunch","afternoon_snack","supper"],
    description: "Type 2 diabetes means your body cannot properly control blood sugar levels. It is managed and even reversed through proper low-sugar, high-fiber eating using Zambian foods.",
    howDietCausesIt: "Eating too much white nshima, sugar, sodas, and refined foods over many years overloads the body's ability to control blood sugar, leading to diabetes.",
    warningSignsText: "Frequent urination, extreme thirst, unexplained weight loss, blurry vision, slow-healing wounds, tingling in hands or feet.",
    whenToSeeDoctor: "See a doctor or clinic immediately if you have very high blood sugar readings, cannot keep food down, feel confused, or have chest pains.",
    keyFoodsToEat: ["bitter_melon","okra","brown_rice","beans","moringa","fish","eggs","vegetables","sorghum_porridge"],
    keyFoodsToAvoid: ["white_nshima","sugar","sodas","honey","white_bread","white_rice","energy_drinks"],
    foodsToLimit: ["sweet_potato","banana","mango"],
    nutritionPriorities: { maximize: ["fiber","protein","vitaminC"], minimize: ["sugar","refined_carbs"] },
    zambian_tip: "Replace white nshima with half-cup brown rice or sorghum porridge. Always pair your carbs with beans or fish to slow sugar absorption."
  },
  {
    id: "hypertension",
    name: "Hypertension",
    shortName: "High BP",
    color: "#E74C3C",
    mealsPerDay: 3,
    mealStructure: ["breakfast","lunch","supper"],
    description: "Hypertension means your blood pressure is too high, putting strain on your heart and blood vessels. It is almost entirely controlled through diet and lifestyle.",
    howDietCausesIt: "Eating too much salt, stock cubes, processed meats, and fried foods causes the body to retain water, raising blood pressure dangerously.",
    warningSignsText: "Severe headaches, nosebleeds, shortness of breath, chest pain, dizziness. Often called a silent killer because there are no early symptoms.",
    whenToSeeDoctor: "See a doctor if your blood pressure reading is above 140/90, you have chest pains, sudden severe headache, or shortness of breath.",
    keyFoodsToEat: ["fish","banana","moringa","garlic","beetroot","hibiscus_tea","leafy_vegetables","lemon"],
    keyFoodsToAvoid: ["salt","stock_cubes","sausages","fried_foods","alcohol","energy_drinks","tinned_foods"],
    foodsToLimit: ["red_meat","cheese","butter"],
    nutritionPriorities: { maximize: ["potassium","fiber","vitaminC"], minimize: ["sodium","saturated_fat"] },
    zambian_tip: "Cook relish without stock cubes or Royco. Use fresh garlic, tomatoes, and onions for flavor instead. Your taste buds adjust within 2 weeks."
  },
  {
    id: "heart_disease",
    name: "Heart Disease",
    shortName: "Heart",
    color: "#C0392B",
    mealsPerDay: 3,
    mealStructure: ["breakfast","lunch","supper"],
    description: "Heart disease means the heart is not pumping blood properly, often due to blocked or narrowed blood vessels. Diet is the most powerful tool to protect and heal the heart.",
    howDietCausesIt: "Fatty meats, sausages, fried foods, and margarine clog arteries with bad cholesterol, gradually blocking blood flow to the heart over years.",
    warningSignsText: "Chest pain or tightness, shortness of breath, pain in left arm or jaw, extreme fatigue, irregular heartbeat.",
    whenToSeeDoctor: "Go to the nearest hospital immediately if you have chest pain, shortness of breath, or feel your heart racing or skipping beats.",
    keyFoodsToEat: ["oats","fish","avocado","garlic","olive_oil","beans","moringa","green_tea","beetroot"],
    keyFoodsToAvoid: ["fatty_meats","sausages","fried_foods","margarine","butter","alcohol","salt"],
    foodsToLimit: ["red_meat","cheese","egg_yolks"],
    nutritionPriorities: { maximize: ["fiber","omega3","potassium"], minimize: ["saturated_fat","sodium","cholesterol"] },
    zambian_tip: "Eat tinned mackerel or fresh bream at least 4 times per week. Omega-3 fats in fish actively repair heart vessels."
  },
  {
    id: "obesity",
    name: "Obesity",
    shortName: "Obesity",
    color: "#D35400",
    mealsPerDay: 3,
    mealStructure: ["breakfast","lunch","supper"],
    description: "Obesity means carrying excess body weight that puts serious strain on the heart, joints, and blood sugar levels. It is managed through portion control and choosing the right Zambian foods.",
    howDietCausesIt: "Eating large portions of nshima, fried foods, sugary drinks, and snacking on chips and sweets provides far more calories than the body needs, stored as fat.",
    warningSignsText: "Difficulty breathing with activity, joint pain especially knees and hips, excessive sweating, snoring, low energy.",
    whenToSeeDoctor: "See a health worker if you have a BMI above 30, cannot walk without pain, or have been told you have high blood pressure or blood sugar along with obesity.",
    keyFoodsToEat: ["vegetables","fish","beans","boiled_chicken","leafy_greens","lemon_water","plain_water"],
    keyFoodsToAvoid: ["nshima","fried_foods","sugar","sodas","peanut_butter","sausages","alcohol"],
    foodsToLimit: ["groundnuts","avocado","fatty_meats"],
    nutritionPriorities: { maximize: ["fiber","protein","water"], minimize: ["calories","fat","sugar"] },
    zambian_tip: "Fill half your plate with vegetables first, then add a small portion of protein. Eat nshima only in the size of your fist."
  },
  {
    id: "kidney_disease",
    name: "Kidney Disease",
    shortName: "Kidney",
    color: "#8E44AD",
    mealsPerDay: 3,
    mealStructure: ["breakfast","lunch","supper"],
    description: "Kidney disease means the kidneys cannot properly filter waste from the blood. Diet must strictly control protein, salt, potassium, and phosphorus to protect the kidneys.",
    howDietCausesIt: "High salt intake, too much protein from meat, and poor blood sugar control over years damage the tiny blood vessels inside the kidneys permanently.",
    warningSignsText: "Swelling in legs and face, reduced urination, foam in urine, extreme fatigue, loss of appetite, nausea.",
    whenToSeeDoctor: "Go to hospital immediately if you stop urinating, have severe swelling, or feel confused and extremely weak.",
    keyFoodsToEat: ["cabbage","cauliflower","white_rice","chicken","eggs","apple","plain_water"],
    keyFoodsToAvoid: ["salt","bananas","beans","dairy_excess","avocado","spinach","dried_fish","kapenta"],
    foodsToLimit: ["potatoes","tomatoes","oranges"],
    nutritionPriorities: { maximize: ["controlled_protein","low_potassium"], minimize: ["sodium","phosphorus","potassium"] },
    zambian_tip: "Boil vegetables and drain the water before eating — this removes much of the potassium. Never use stock cubes or salt in cooking."
  },
  {
    id: "osteoporosis",
    name: "Osteoporosis",
    shortName: "Bone Health",
    color: "#7F8C8D",
    mealsPerDay: 3,
    mealStructure: ["breakfast","lunch","supper"],
    description: "Osteoporosis means bones have become thin and brittle, breaking easily. Building strong bones requires calcium and Vitamin D from food every single day.",
    howDietCausesIt: "Years of low calcium intake, too many sodas, excessive alcohol, and not enough sun exposure cause bones to slowly lose their density.",
    warningSignsText: "Back pain from collapsed vertebrae, loss of height over time, stooped posture, fractures from minor falls.",
    whenToSeeDoctor: "See a doctor if you have a fracture from a minor fall, lose more than 2cm of height, or have severe back pain.",
    keyFoodsToEat: ["kapenta","milk","moringa","kale","yoghurt","baobab","cheese","sardines"],
    keyFoodsToAvoid: ["alcohol","sodas","excessive_coffee","excessive_salt"],
    foodsToLimit: ["tea","coffee"],
    nutritionPriorities: { maximize: ["calcium","vitaminD","protein"], minimize: ["sodium","alcohol","phosphoric_acid"] },
    zambian_tip: "Eat kapenta with the bones — that is where most of the calcium is. Do not remove small bones from small fish."
  },
  {
    id: "liver_disease",
    name: "Liver Disease",
    shortName: "Liver",
    color: "#884EA0",
    mealsPerDay: 4,
    mealStructure: ["breakfast","morning_snack","lunch","supper"],
    description: "Liver disease means the liver cannot properly clean the blood and produce vital nutrients. The liver has remarkable ability to heal when given the right foods.",
    howDietCausesIt: "Alcohol is the leading cause of liver damage in Zambia. Fatty foods and processed foods also force the liver to work overtime, causing fatty liver disease.",
    warningSignsText: "Yellowing of skin or eyes (jaundice), extreme fatigue, swollen abdomen, dark urine, pale stools, loss of appetite.",
    whenToSeeDoctor: "Go to hospital immediately if you see yellow eyes or skin, have severe abdominal swelling, or vomit blood.",
    keyFoodsToEat: ["fish","moringa","beetroot","lemon","garlic","green_tea","turmeric","avocado"],
    keyFoodsToAvoid: ["alcohol","fatty_meats","fried_foods","processed_foods","sodas"],
    foodsToLimit: ["red_meat","salt","sugar"],
    nutritionPriorities: { maximize: ["antioxidants","protein","fiber"], minimize: ["fat","alcohol","processed_foods"] },
    zambian_tip: "Drink warm lemon water every morning before eating. Lemon activates bile flow and helps the liver begin its daily cleaning work."
  },
  {
    id: "colon_cancer",
    name: "Colon Cancer Prevention",
    shortName: "Colon Cancer",
    color: "#1A5276",
    mealsPerDay: 3,
    mealStructure: ["breakfast","lunch","supper"],
    description: "Colon cancer prevention through diet is possible. High-fiber Zambian foods protect the colon by keeping waste moving quickly and reducing harmful bacteria.",
    howDietCausesIt: "Low-fiber diets with too much red meat, processed meats, and alcohol cause waste to stay in the colon too long, exposing colon walls to harmful substances.",
    warningSignsText: "Blood in stool, changes in bowel habits lasting more than 4 weeks, persistent abdominal pain, unexplained weight loss, fatigue.",
    whenToSeeDoctor: "See a doctor if you notice blood in your stool, a sudden change in bowel habits, or persistent abdominal pain lasting more than 3 weeks.",
    keyFoodsToEat: ["beans","oats","broccoli","fish","guava","garlic","vegetables","brown_rice"],
    keyFoodsToAvoid: ["red_meat","sausages","alcohol","refined_foods","fried_foods"],
    foodsToLimit: ["processed_meats","white_bread"],
    nutritionPriorities: { maximize: ["fiber","antioxidants","vitaminC"], minimize: ["red_meat","alcohol","processed_food"] },
    zambian_tip: "Eat beans as relish at least 4 times per week. The fiber in beans is the most powerful colon protector in the Zambian diet."
  },
  {
    id: "stroke",
    name: "Stroke Prevention",
    shortName: "Stroke",
    color: "#922B21",
    mealsPerDay: 3,
    mealStructure: ["breakfast","lunch","supper"],
    description: "Stroke prevention means protecting blood vessels in the brain. Most strokes are preventable through a low-salt, high-vegetable diet.",
    howDietCausesIt: "High blood pressure from too much salt and fatty foods damages brain blood vessels. One burst vessel causes a stroke with permanent damage in minutes.",
    warningSignsText: "Sudden numbness in face, arm, or leg especially on one side. Sudden confusion, trouble speaking, trouble seeing, severe headache.",
    whenToSeeDoctor: "Call for help immediately — stroke is a medical emergency. Every minute counts. Get to hospital within 3 hours of first symptoms.",
    keyFoodsToEat: ["fish","ginger","garlic","beetroot","banana","moringa","leafy_vegetables","hibiscus_tea"],
    keyFoodsToAvoid: ["salt","fatty_foods","alcohol","energy_drinks","stock_cubes","fried_foods"],
    foodsToLimit: ["red_meat","dairy_fat"],
    nutritionPriorities: { maximize: ["potassium","omega3","fiber"], minimize: ["sodium","saturated_fat","alcohol"] },
    zambian_tip: "Have your blood pressure checked at your nearest clinic once a month. Most strokes happen because high blood pressure was never noticed."
  },
  {
    id: "gout",
    name: "Gout",
    shortName: "Gout",
    color: "#2E86C1",
    mealsPerDay: 3,
    mealStructure: ["breakfast","lunch","supper"],
    description: "Gout causes sudden severe joint pain, usually in the big toe, from uric acid crystals forming in joints. Avoiding certain foods prevents attacks completely.",
    howDietCausesIt: "Organ meats, kapenta, dried fish, and alcohol cause high uric acid levels in blood. When the body cannot clear it, crystals form in joints causing extreme pain.",
    warningSignsText: "Sudden intense pain in big toe, swollen and red joint, unable to bear weight on the affected foot, warmth in the joint.",
    whenToSeeDoctor: "See a health worker if joint pain is severe, you have fever with joint pain, or attacks happen more than twice a year.",
    keyFoodsToEat: ["eggs","chicken","dairy","lemon_water","vegetables","plain_water","fruits"],
    keyFoodsToAvoid: ["organ_meats","kapenta_dried","dried_fish","alcohol","spinach","beans","anchovies"],
    foodsToLimit: ["meat_in_general","seafood"],
    nutritionPriorities: { maximize: ["water","vitaminC","dairy"], minimize: ["purines","alcohol","fructose"] },
    zambian_tip: "Drink at least 2 litres of plain water every day. Water flushes uric acid out of the blood before it can form crystals in joints."
  },
  {
    id: "anaemia",
    name: "Anaemia",
    shortName: "Anaemia",
    color: "#E74C3C",
    mealsPerDay: 3,
    mealStructure: ["breakfast","lunch","supper"],
    description: "Anaemia means the blood does not have enough iron to carry oxygen around the body, causing constant fatigue and weakness. It is very common in Zambia and entirely fixable through food.",
    howDietCausesIt: "Iron-poor diets, drinking tea with meals, and worm infections all cause anaemia. Women and children are most at risk.",
    warningSignsText: "Extreme tiredness, pale skin and eyes, shortness of breath with activity, fast heartbeat, dizziness, cold hands and feet.",
    whenToSeeDoctor: "See a nurse if you feel faint, have a very fast heartbeat at rest, are pregnant and feel extremely tired, or if a child is very pale.",
    keyFoodsToEat: ["liver","kapenta","beans","moringa","bondwe","amaranth","beetroot","lemon"],
    keyFoodsToAvoid: ["tea_with_meals","coffee_with_meals","alcohol","sodas"],
    foodsToLimit: [],
    nutritionPriorities: { maximize: ["iron","vitaminC","protein"], minimize: ["tannins_with_iron_foods"] },
    zambian_tip: "Always add a squeeze of lemon or eat an orange with your iron-rich meal. Vitamin C doubles the amount of iron your body absorbs."
  },
  {
    id: "malnutrition",
    name: "Malnutrition",
    shortName: "Malnutrition",
    color: "#27AE60",
    mealsPerDay: 5,
    mealStructure: ["breakfast","morning_snack","lunch","afternoon_snack","supper"],
    description: "Malnutrition means the body is not getting enough calories, protein, and vitamins to grow and function properly. It is most dangerous in children under 5.",
    howDietCausesIt: "Eating only nshima without protein or vegetables, food insecurity, and diarrhea disease all cause malnutrition by depriving the body of what it needs to grow.",
    warningSignsText: "In children: thin limbs, swollen abdomen, hair loss, failure to grow, constant sickness. In adults: extreme thinness, muscle wasting, fatigue.",
    whenToSeeDoctor: "Take a child to the nearest health post immediately if they have swollen legs, cannot eat, or have not grown in 3 months.",
    keyFoodsToEat: ["eggs","groundnuts","soya","milk","moringa","liver","beans","fish","peanut_butter"],
    keyFoodsToAvoid: ["sodas","candy","chips","alcohol"],
    foodsToLimit: [],
    nutritionPriorities: { maximize: ["protein","calories","iron","vitaminA","zinc"], minimize: ["empty_calories"] },
    zambian_tip: "Add groundnut powder or moringa powder to porridge every day. These two foods together provide protein, iron, and vitamins all at once."
  },
  {
    id: "gastritis",
    name: "Gastritis & Stomach Ulcers",
    shortName: "Gastritis",
    color: "#F39C12",
    mealsPerDay: 5,
    mealStructure: ["breakfast","morning_snack","lunch","afternoon_snack","supper"],
    description: "Gastritis and stomach ulcers mean the stomach lining is damaged or inflamed, causing burning pain. Eating gentle, soothing foods allows the stomach to heal.",
    howDietCausesIt: "Spicy foods, alcohol, coffee, pain medications, and the H.pylori bacterium damage the stomach lining, causing chronic pain and ulcers.",
    warningSignsText: "Burning or gnawing stomach pain, nausea, vomiting, feeling full quickly, loss of appetite, black or bloody stools.",
    whenToSeeDoctor: "Go to hospital if you vomit blood, have black tarry stools, feel severe stomach pain that does not stop, or lose significant weight.",
    keyFoodsToEat: ["oats","banana","cabbage_juice","plain_yoghurt","pawpaw","honey","boiled_potato","soft_foods"],
    keyFoodsToAvoid: ["spicy_food","alcohol","coffee","citrus","raw_onion","fried_foods","vinegar"],
    foodsToLimit: ["tomatoes","garlic","ginger"],
    nutritionPriorities: { maximize: ["soft_foods","probiotics","fiber"], minimize: ["acid","spice","alcohol","caffeine"] },
    zambian_tip: "Eat a small meal every 3 hours instead of 3 large ones. An empty stomach produces acid that burns the already-damaged lining."
  },
  {
    id: "vitamin_a",
    name: "Vitamin A Deficiency",
    shortName: "Vitamin A",
    color: "#F1C40F",
    mealsPerDay: 3,
    mealStructure: ["breakfast","lunch","supper"],
    description: "Vitamin A deficiency causes night blindness, weakened immunity, and in children, severe eye damage. It is prevented entirely by eating orange and dark green Zambian foods.",
    howDietCausesIt: "Diets with no orange sweet potato, moringa, carrots, or leafy vegetables lead to Vitamin A deficiency, especially in children in rural areas.",
    warningSignsText: "Poor night vision, dry eyes, frequent infections and illness, dry rough skin, slow wound healing.",
    whenToSeeDoctor: "Take a child to the health post immediately if they cannot see in low light, have very dry eyes, or get sick repeatedly every month.",
    keyFoodsToEat: ["orange_sweet_potato","moringa","carrots","liver","pumpkin","mango","papaya","kale","chibwabwa"],
    keyFoodsToAvoid: [],
    foodsToLimit: [],
    nutritionPriorities: { maximize: ["vitaminA","vitaminC","fat_for_absorption"], minimize: [] },
    zambian_tip: "Always add a spoonful of cooking oil when eating Vitamin A foods — your body needs fat to absorb this vitamin. Orange sweet potato cooked in oil is perfect."
  },
  {
    id: "cholesterol",
    name: "High Cholesterol",
    shortName: "Cholesterol",
    color: "#E67E22",
    mealsPerDay: 3,
    mealStructure: ["breakfast","lunch","supper"],
    description: "High cholesterol means there is too much bad fat in the blood, slowly clogging arteries and leading to heart attack and stroke. Diet is the most powerful treatment.",
    howDietCausesIt: "Fatty meats, sausages, fried foods, egg yolks in excess, and margarine all raise bad cholesterol levels in the blood over time.",
    warningSignsText: "High cholesterol has NO symptoms until it causes a heart attack or stroke. Regular blood tests are the only way to detect it.",
    whenToSeeDoctor: "Ask for a cholesterol blood test at any clinic. Everyone over 35 should be tested at least once.",
    keyFoodsToEat: ["oats","beans","fish","avocado","moringa","garlic","brown_rice","vegetables","apples"],
    keyFoodsToAvoid: ["fatty_meats","sausages","fried_foods","egg_yolks_excess","margarine","butter"],
    foodsToLimit: ["red_meat","coconut_oil","cheese"],
    nutritionPriorities: { maximize: ["soluble_fiber","omega3","antioxidants"], minimize: ["saturated_fat","trans_fat","cholesterol"] },
    zambian_tip: "Eat oats for breakfast every day. Oats contain beta-glucan, a fiber that actively binds and removes bad cholesterol from your blood."
  },
  {
    id: "diabetes_type1",
    name: "Type 1 Diabetes",
    shortName: "Diabetes T1",
    color: "#C0392B",
    mealsPerDay: 5,
    mealStructure: ["breakfast","morning_snack","lunch","afternoon_snack","supper"],
    description: "Type 1 diabetes means the body produces no insulin at all and requires daily insulin injections. Diet must be carefully controlled to keep blood sugar stable between injections.",
    howDietCausesIt: "Type 1 is not caused by diet — it is an autoimmune condition. However, diet determines how well it is managed. Wrong foods cause dangerous blood sugar swings.",
    warningSignsText: "Extreme thirst, frequent urination, sudden weight loss, very high blood sugar reading, vomiting, fruity breath odor.",
    whenToSeeDoctor: "Go to hospital immediately if blood sugar is very high or very low, if you are vomiting and cannot keep food down, or if you run out of insulin.",
    keyFoodsToEat: ["vegetables","beans","brown_rice","fish","chicken","eggs","moringa"],
    keyFoodsToAvoid: ["sugar","white_nshima","sodas","sweets","honey","white_bread","juice"],
    foodsToLimit: ["fruit","sweet_potato","rice"],
    nutritionPriorities: { maximize: ["fiber","protein","low_glycemic_foods"], minimize: ["sugar","refined_carbs","high_glycemic"] },
    zambian_tip: "Never skip a meal when on insulin. Eat your meals at exactly the same time every day so your insulin dose can be accurately timed."
  },
  {
    id: "celiac",
    name: "Celiac Disease",
    shortName: "Celiac",
    color: "#1A8A50",
    mealsPerDay: 3,
    mealStructure: ["breakfast","lunch","supper"],
    description: "Celiac disease means eating wheat, barley, or rye gluten triggers an immune attack on the intestine. Complete avoidance of gluten allows full recovery.",
    howDietCausesIt: "Gluten in wheat flour, bread, chapati, and semolina triggers intestinal damage in celiac patients. Even small amounts cause harm.",
    warningSignsText: "Chronic diarrhea, bloating, weight loss, fatigue, anemia, rash, bone pain. Symptoms worsen with any wheat or bread consumption.",
    whenToSeeDoctor: "See a doctor for blood tests if you have chronic diarrhea, weight loss, and fatigue together that improves when you avoid bread and wheat.",
    keyFoodsToEat: ["rice","cassava","sweet_potato","fish","eggs","beans","vegetables","fruits","sorghum","millet"],
    keyFoodsToAvoid: ["wheat_flour","bread","chapati","semolina","samp","nshima","mandazi","vitumbuwa","biscuits"],
    foodsToLimit: [],
    nutritionPriorities: { maximize: ["gluten_free_carbs","protein","iron"], minimize: ["gluten","wheat","barley"] },
    zambian_tip: "Rice and cassava are completely gluten-free and perfect for celiac. Make nshima from cassava flour instead of maize — it looks the same and tastes similar."
  },
  {
    id: "iron_overload",
    name: "Iron Overload",
    shortName: "Iron Overload",
    color: "#922B21",
    mealsPerDay: 3,
    mealStructure: ["breakfast","lunch","supper"],
    description: "Iron overload (hemochromatosis) means the body stores too much iron, damaging organs. Unlike most Zambian conditions, this requires limiting iron-rich foods.",
    howDietCausesIt: "A genetic condition causes excessive iron absorption. Eating liver, kapenta, and red meat in this condition speeds up organ damage.",
    warningSignsText: "Joint pain, fatigue, abdominal pain, bronze skin color, liver problems, irregular heartbeat.",
    whenToSeeDoctor: "See a doctor for a serum ferritin blood test if you have persistent joint pain, fatigue, and a family history of iron overload.",
    keyFoodsToEat: ["vegetables","white_rice","chicken","dairy","eggs","tea"],
    keyFoodsToAvoid: ["red_meat","liver","kapenta","fortified_foods","vitamin_c_with_iron_foods"],
    foodsToLimit: ["beans","spinach","fish"],
    nutritionPriorities: { maximize: ["calcium","dairy","tea_inhibitors"], minimize: ["heme_iron","vitamin_c_with_meals"] },
    zambian_tip: "Drink black tea or milk with iron-containing meals. Both naturally block iron absorption and help prevent dangerous iron buildup."
  },
  {
    id: "thyroid",
    name: "Thyroid Disease",
    shortName: "Thyroid",
    color: "#5D6D7E",
    mealsPerDay: 3,
    mealStructure: ["breakfast","lunch","supper"],
    description: "Hypothyroid means the thyroid gland is underactive and produces too little thyroid hormone, causing extreme fatigue, weight gain, and cold sensitivity.",
    howDietCausesIt: "Iodine deficiency causes goiter and hypothyroid. Certain foods — cassava, cabbage, soya — eaten in excess can suppress thyroid function further.",
    warningSignsText: "Extreme fatigue, weight gain without eating more, always feeling cold, constipation, dry skin and hair, depression, slow heartbeat.",
    whenToSeeDoctor: "See a doctor for a thyroid blood test if you have persistent fatigue, unexplained weight gain, and always feel cold despite the weather.",
    keyFoodsToEat: ["fish","eggs","dairy","fruits","vegetables","iodized_salt","seaweed_if_available"],
    keyFoodsToAvoid: ["cassava_leaves_excess","cabbage_raw","soya_excess","millet_excess"],
    foodsToLimit: ["cassava","kale","broccoli","cauliflower"],
    nutritionPriorities: { maximize: ["iodine","selenium","zinc"], minimize: ["goitrogens"] },
    zambian_tip: "Always use iodized salt in your cooking — iodine is essential for thyroid hormone production. Cook goitrogenic vegetables like cassava leaves thoroughly to reduce their impact."
  },
  {
    id: "general",
    name: "General Healthy Eating",
    shortName: "Healthy",
    color: "#27AE60",
    mealsPerDay: 3,
    mealStructure: ["breakfast","lunch","supper"],
    description: "You have no specific condition — this is your opportunity to prevent disease through excellent daily nutrition. A balanced Zambian diet can protect you from all 20 conditions in this app.",
    howDietCausesIt: "Poor eating habits today are the leading cause of diabetes, hypertension, and heart disease tomorrow. Every good meal is an act of prevention.",
    warningSignsText: "Watch for sudden weight gain, increased thirst, fatigue without reason, or high blood pressure — these are early warning signs.",
    whenToSeeDoctor: "Have a general health check once a year including blood pressure, blood sugar, and weight measurements.",
    keyFoodsToEat: ["variety_of_vegetables","fish","beans","fruits","moringa","whole_grains","plain_water"],
    keyFoodsToAvoid: ["excessive_sugar","excessive_salt","fried_foods","alcohol","sodas"],
    foodsToLimit: ["red_meat","white_nshima"],
    nutritionPriorities: { maximize: ["variety","fiber","protein","vitamins"], minimize: ["excess_sugar","excess_salt","excess_fat"] },
    zambian_tip: "Aim for 5 different colored vegetables or fruits every day. Each color provides different vitamins and minerals your body needs to stay healthy."
  }
];

export function getConditionById(id) {
  return CONDITIONS.find(c => c.id === id);
}

export function getForbiddenFoodIds(conditionId) {
  const condition = getConditionById(conditionId);
  return condition ? condition.keyFoodsToAvoid : [];
}

export function getMealStructure(conditionId) {
  const condition = getConditionById(conditionId);
  return condition ? condition.mealStructure : ["breakfast","lunch","supper"];
}

export function getMealsPerDay(conditionId) {
  const condition = getConditionById(conditionId);
  return condition ? condition.mealsPerDay : 3;
}

export const CONDITION_IDS = CONDITIONS.map(c => c.id);
export const CONDITION_NAMES = CONDITIONS.map(c => ({ id: c.id, name: c.name }));
